---
- name: Install tools and wordlists on VM
  hosts: all
  become: yes

  vars:
    tools:
      - nmap
      - gobuster
      - hydra
      - openvpn
      - wget
      - curl
      - ssh
      - git
      - python3
      - tcpdump
      - sqlmap
      - ffuf
      - john
    rockyou_url: https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
    rockyou_dest: /usr/share/wordlists/rockyou.txt

  tasks:
    - name: Update apt package manager
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install required tools
      apt:
        name: "{{ tools }}"
        state: latest
        force_apt_get: yes

    - name: Install unzip package
      apt:
        name: unzip
        state: present

    - name: Create wordlist directory if it doesn't exist
      file:
        path: /usr/share/wordlists
        state: directory
        mode: '0755'

    - name: Download SecLists master zip file
      get_url:
        url: https://github.com/danielmiessler/SecLists/archive/master.zip
        dest: /tmp/SecList.zip
        mode: '0644'

    - name: Unzip SecLists zip file
      unarchive:
        src: /tmp/SecList.zip
        dest: /usr/share/wordlists/
        remote_src: yes
        creates: /usr/share/wordlists/SecLists-master

    - name: Remove the zip file after extraction
      file:
        path: /tmp/SecList.zip
        state: absent

    - name: Download rockyou.txt wordlist
      get_url:
        url: "{{ rockyou_url }}"
        dest: "{{ rockyou_dest }}"
        mode: '0644'

    - name: Verify rockyou.txt is downloaded
      stat:
        path: "{{ rockyou_dest }}"
      register: rockyou_stat

    - name: Display rockyou.txt path
      debug:
        msg: "rockyou.txt is downloaded to {{ rockyou_dest }}"
      when: rockyou_stat.stat.exists

    - name: Ensure OpenVPN service is enabled and ready
      systemd:
        name: openvpn
        enabled: yes
        state: stopped

    - name: Display OpenVPN ready status
      debug:
        msg: "OpenVPN is installed and ready for manual configuration."
